### ISSUE TITLE
Trouble building on Windows

### ISSUE THREAD

**Issue by nikhilsinha** [scala/scala-xml#71] opened 2015-07-28 22:46 UTC
Hello,

I run sbt in the root directory of scala-xml, but it's unable to find scala.xml.Properties.  I'm unable to find it also.  Given the name, I think it would be in the pull.  Is something missing from source control?  Or am I missing a dependency?

Edit: Using Windows 8.1, Scala 2.11.7, and sbt 0.13.8.  

Here's the output of the compile:

[info] Compiling 84 Scala sources to C:\dev\scala-xml\target\scala-2.12.0-M2\cla
sses...
[info] 'compiler-interface' not yet compiled for Scala 2.12.0-M2. Compiling...
[info]   Compilation completed in 11.349 s
[info] Running scala.xml.Properties
[error] (run-main-0) java.lang.ClassNotFoundException: scala.xml.Properties
java.lang.ClassNotFoundException: scala.xml.Properties
[trace] Stack trace suppressed: run last compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code: 1
[error] Total time: 70 s, completed Jul 28, 2015 6:32:38 PM

Here's what I get from last compile:run

[info] Running scala.xml.Properties
[debug] Waiting for threads to exit or System.exit to be called.
[debug]   Classpath:
[debug]         C:\dev\scala-xml\target\scala-2.12.0-M2\classes
[debug]         C:\Users\Nikhil\.ivy2\cache\org.scala-lang\scala-library\jars\sc
ala-library-2.12.0-M2.jar
[debug] Waiting for thread run-main-0 to terminate.
[error] (run-main-0) java.lang.ClassNotFoundException: scala.xml.Properties
java.lang.ClassNotFoundException: scala.xml.Properties
        at sbt.classpath.ClasspathFilter.loadClass(ClassLoaders.scala:63)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at sbt.Run.getMainMethod(Run.scala:72)
        at sbt.Run.run0(Run.scala:60)
        at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
        at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
        at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
        at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
        at sbt.Logger$$anon$4.apply(Logger.scala:85)
        at sbt.TrapExit$App.run(TrapExit.scala:248)
        at java.lang.Thread.run(Thread.java:745)
[debug]         Thread run-main-0 exited.
[debug] Interrupting remaining threads (should be all daemons).
[debug] Sandboxed run complete..
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
        at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:1943)
        at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:1943)
        at scala.Option.foreach(Option.scala:236)
        at sbt.BuildCommon$class.toError(Defaults.scala:1943)
        at sbt.Defaults$.toError(Defaults.scala:38)
        at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$36$$anonfun$apply$37.a
pply(Defaults.scala:719)
        at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$36$$anonfun$apply$37.a
pply(Defaults.scala:717)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:22
6)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:22
6)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestric
tions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (compile:run) Nonzero exit code: 1

**Comment by biswanaths** [comment] 2015-07-29 05:46
Generally, when I found classnotfound exception they tended to be version mismatch issues, between scala version and library build for another version. 

P.S. This observation is anecdotal, and might not be relevant to your issue.

**Comment by nikhilsinha** [comment] 2015-07-29 14:48
Ok, so scala.xml.Properties in in XML.scala, and I can see the Properties.class and Properties$.class in target\scala-2.12.0-M2\classes\scala\xml.

Which items should I check the version number of?

**Comment by nikhilsinha** [comment] 2015-07-29 15:21
Actually, I have Scala 2.11.7, but the build seems to be using 2.12.0-M2.  How would that happen?

**Comment by SethTisue** [comment] 2015-07-29 18:53
in general with sbt, it doesn't matter what version of Scala you "have" on your computer, and it isn't necessary to have any versions of Scala installed at all. the Scala versions used by an sbt-based build are determined, obtained, and controlled entirely by sbt, as configured in the individual project's build.

in the scala-xml project in particular, in `build.sbt` we see:

```scala
scalaVersion               := crossScalaVersions.value.head

crossScalaVersions         := {
  val java = System.getProperty("java.version")
  if (java.startsWith("1.6."))
    Seq("2.11.7", "2.12.0-M1")
  else if (java.startsWith("1.8."))
    Seq("2.12.0-M2")
  else
    sys.error(s"don't know what Scala versions to build on $java")
}
```

if you're building for Scala 2.11, you should be doing it using JDK 6, not 8. at least, that's what the above code expects. it's my code and I describe it at https://github.com/SethTisue/scala-partest/pull/1 as "a crummy hack"; the maintainers of this repo should feel free to do better (perhaps along the lines Lukas suggests in that PR), but any changes that are made need to be made carefully so they don't break our Travis-based system for publishing scala-xml releases.

as for you on your Windows system, the safest course is to obtain and use JDK 6 for this, since that's how any changes you make, if they are accepted, will ultimately be built and tested. but if you just want to get up and running on JDK 8 and not worry about it for now, the alternative would be to edit build.sbt and set `scalaVersion` appropriately; just don't include the change in any pull requests you send.

**Comment by SethTisue** [comment] 2015-07-29 18:57
P.S sorry this is all a bit complicated, but that's life for library authors needing to support multiple Scala versions and multiple JDKs. an alternative is not to use sbt's cross-building features, and just have different branches. that approach has its own downsides — you end up having do a lot of error-prone merging of changes from branch to branch.

**Comment by SethTisue** [comment] 2015-07-29 19:03
Ha... I haven't even addressed your original question yet, which is why are you getting the error you're getting? It actually doesn't have anything to do with the Scala version question. The error is simply because you're trying to run the `run` command, but that isn't actually supported in this repo. I get the same error if I try `run` on my Mac; it isn't a Windows-specific thing.

you don't need `run`, just other standard sbt commands like `compile`, `test`, `package` if you want to make a jar, etc.

closing the issue as this is not a bug.

**Closed by SethTisue** 2015-07-29 19:03 UTC

**Comment by nikhilsinha** [comment] 2015-07-29 19:27
Ok, that fixed it.

**Comment by biswanaths** [comment] 2015-07-30 05:30
@SethTisue , maintainers got noted about the crossbuilding.  I will dig more about the cross building and look around the PR you mentioned.

**Comment by nikhilsinha** [comment] 2015-07-30 12:38
It turns out the problem was using compile vs run.  On Linux, I get the same errors if I use run.  It would be nice to have a Getting Started page, that just had some simple instructions on how to compile it.

As of right now, I just have one unit test failing.  scala.xml.XMLTest.ioPosition.  I'm going to assume this is a broken test and not worry about it.

[error] Test scala.xml.XMLTest.ioPosition failed: expected:<... instead of ' '
  ^[
[error] :1:5: name expected, but char ' ' cannot start a name    ^
[error] expected closing tag of foo]
[error] > but was:<... instead of ' '    ^[
[error] :1:5: name expected, but char ' ' cannot start a name    ^
]error] expected closing tag of foo
[error] >
[error] Failed: Total 90, Failed 1, Errors 0, Passed 89
[error] Failed tests:
[error]         scala.xml.XMLTest
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 8 s, completed Jul 29, 2015 3:25:22 PM

**Comment by SethTisue** [comment] 2015-08-04 18:23
@nikhilsinha I'd suggest opening a separate ticket on the test failure, actually. I don't know what that's about.

**Comment by biswanaths** [comment] 2015-08-05 10:15
@nikhilsinha As suggest by @SethTisue please open an issue. I am assuming the new line in the string is interpreted differently in your test runs. 

Please do provide the information on your platform, test run. Like are you seeing the error in windows or linux or both. 

Might be git line ending issue. https://help.github.com/articles/dealing-with-line-endings/
